<a href="https://colab.research.google.com/github/santr4/pytorch_for_deep_learning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [38]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensors

## creating tensors

In [39]:
# scalar -> it is a 0D tensor which can contain anything like an integer, float, etc.
scalar = torch.tensor(7)
scalar

tensor(7)

In [40]:
scalar.ndim

0

In [41]:
var = np.array(3)
print(var.ndim)

0


In [42]:
# to get integer from tensor
scalar.item()

7

In [43]:
# vectors
vector = torch.tensor([8,6])
vector


tensor([8, 6])

In [44]:
vector.shape

torch.Size([2])

In [45]:
# count the number of opening square brackets in the tensor that will give the dimensions of the tensor.
vector.ndim


1

 For matrix and tensors we use capital letters and for vectors and scalars we use small letters.

In [46]:
# matrix
M = torch.tensor([[4,5,3],
                  [1,2,3]])

M

tensor([[4, 5, 3],
        [1, 2, 3]])

In [47]:
M.ndim

2

In [48]:
M.shape

torch.Size([2, 3])

In [49]:
M[1][2]

tensor(3)

In [50]:
v = M[1][2]
v.type()

'torch.LongTensor'

In [51]:
# Tensors
T = torch.tensor([[[3,4,5],
                   [6,7,8],
                   [9,8,0]]])
T

tensor([[[3, 4, 5],
         [6, 7, 8],
         [9, 8, 0]]])

In [52]:
T.ndim

3

In [53]:
T.shape

torch.Size([1, 3, 3])

### random tensors

In [54]:
random_tensor = torch.rand(4,5)
random_tensor

tensor([[0.3946, 0.6889, 0.7214, 0.6553, 0.3566],
        [0.8809, 0.6532, 0.5870, 0.9515, 0.8107],
        [0.4469, 0.2213, 0.5115, 0.9000, 0.0319],
        [0.6552, 0.1609, 0.3093, 0.4199, 0.9182]])

In [55]:
random_tensor.ndim

2

In [56]:
random_tensor.shape

torch.Size([4, 5])

In [57]:
# now lets see how we represent an image in tensor format.
random_image_tensor = torch.rand(size=(256, 256, 3)) # 256 - height, 256 - width, 3 colors means 3 channels - RGB.
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([256, 256, 3]), 3)

In [58]:
T2 = torch.rand(3, 2, 1, 4)
T2

tensor([[[[0.9241, 0.3600, 0.2065, 0.8683]],

         [[0.1164, 0.6994, 0.3454, 0.1463]]],


        [[[0.8663, 0.2865, 0.9489, 0.4390]],

         [[0.5837, 0.1087, 0.7271, 0.8397]]],


        [[[0.4868, 0.1679, 0.6103, 0.3293]],

         [[0.2306, 0.8581, 0.0305, 0.9586]]]])

In [59]:
T2.ndim, T2.shape

(4, torch.Size([3, 2, 1, 4]))

### Zeroes and Ones

In [60]:
z = torch.zeros(3, 4)
o = torch.ones(3, 4)
z, o

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [61]:
z.dtype # default datatype is 32-bit integer.

torch.float32

In [62]:
V = torch.tensor([[[1,2,3],
                  [3.0, 6.0, 7.0],
                  [4,5,6]]])
V

tensor([[[1., 2., 3.],
         [3., 6., 7.],
         [4., 5., 6.]]])

In [63]:
V.shape

torch.Size([1, 3, 3])

In [64]:
V.ndim

3

In [65]:
V.size  # it's a function.

<function Tensor.size>

In [66]:
data_type = V.dtype
print(data_type)

torch.float32


### Random Tensors


In [67]:
random_tensor = torch.rand(size=(2,4,3))
random_tensor


tensor([[[0.2844, 0.0450, 0.7643],
         [0.3263, 0.5201, 0.7171],
         [0.4618, 0.4028, 0.1456],
         [0.5309, 0.9998, 0.8341]],

        [[0.3719, 0.0082, 0.8293],
         [0.6696, 0.8221, 0.7226],
         [0.8648, 0.0834, 0.6256],
         [0.3831, 0.4130, 0.5196]]])

In [68]:
random_tensor.dtype

torch.float32

In [69]:
B1 = torch.empty(3,2)
B1

tensor([[2.6838e+23, 3.0764e-41],
        [2.2200e+23, 3.0764e-41],
        [8.9683e-44, 0.0000e+00]])

In [71]:
B1_zeros = torch.zeros_like(B1)
B1_zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [76]:
B2 = torch.arange(start=1, end = 11, step =  2)
B2

tensor([1, 3, 5, 7, 9])

In [77]:
B3 = torch.tensor([3.0, 6.0, 9.0], dtype = None, device = None, requires_grad = False)

In [78]:
B3.dtype

torch.float32

In [79]:
B3 = B3.type(torch.float16)
B3

tensor([3., 6., 9.], dtype=torch.float16)

In [81]:
B4 = torch.tensor([1,2,3], dtype=torch.uint8)

In [83]:
B3 * B4  # here tensors with two different data types are getting multiplied together.

tensor([ 3., 12., 27.], dtype=torch.float16)

### Manipulating tensors

In [85]:
sample_tensor = torch.tensor([1,3,4])
# Addition
sample_tensor + 10

tensor([0.1000, 0.3000, 0.4000])

In [86]:
# Subtraction
sample_tensor - 10

tensor([-9, -7, -6])

In [87]:
# Multiplication
sample_tensor * 10


tensor([10, 30, 40])

In [88]:
# Division
sample_tensor / 10

tensor([0.1000, 0.3000, 0.4000])

In [89]:
# Element Multiplication
some_tensor = torch.tensor([1, 2, 3])
some_tensor * some_tensor


tensor([1, 4, 9])

In [90]:
# Matrix Multiplication or Dot Product
some_tensor.matmul(some_tensor)

tensor(14)

In [91]:
%%time
v = 0
for i in range(len(some_tensor)):
  v += some_tensor[i] * some_tensor[i]
v

CPU times: user 1.1 ms, sys: 992 µs, total: 2.09 ms
Wall time: 6.26 ms


tensor(14)

In [92]:
%%time
torch.matmul(some_tensor, some_tensor)

CPU times: user 1.23 ms, sys: 0 ns, total: 1.23 ms
Wall time: 1.25 ms


tensor(14)

In [93]:
torch.matmul(torch.rand(3,2), torch.rand(2,4))

tensor([[0.0259, 0.1133, 0.0906, 0.0695],
        [0.2389, 0.9536, 1.0529, 0.8052],
        [0.1456, 0.6228, 0.5421, 0.4158]])

In [95]:
# One of the common ways you can remove the errors in matrix multiplication is using transpose
C1 = torch.tensor([[1,2,2],
                  [2,3,4]])
C1.shape

torch.Size([2, 3])

In [97]:
C2 = torch.tensor([[5,6,7],
                   [7,8,9]])
C2.shape

torch.Size([2, 3])

In [99]:
# torch.matmul(c1, c2) -> this will throw error as the inner dimensions dont match
torch.matmul(C1, C2.T)

tensor([[31, 41],
        [56, 74]])

In [101]:
C2.T, C2.T.shape

(tensor([[5, 7],
         [6, 8],
         [7, 9]]),
 torch.Size([3, 2]))