<a href="https://colab.research.google.com/github/santr4/pytorch_for_deep_learning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensors

## creating tensors

In [4]:
# scalar -> it is a 0D tensor which can contain anything like an integer, float, etc.
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
var = np.array(3)
print(var.ndim)

0


In [7]:
# to get integer from tensor
scalar.item()

7

In [8]:
# vectors
vector = torch.tensor([8,6])
vector


tensor([8, 6])

In [9]:
vector.shape

torch.Size([2])

In [10]:
# count the number of opening square brackets in the tensor that will give the dimensions of the tensor.
vector.ndim


1

 For matrix and tensors we use capital letters and for vectors and scalars we use small letters.

In [11]:
# matrix
M = torch.tensor([[4,5,3],
                  [1,2,3]])

M

tensor([[4, 5, 3],
        [1, 2, 3]])

In [12]:
M.ndim

2

In [13]:
M.shape

torch.Size([2, 3])

In [14]:
M[1][2]

tensor(3)

In [15]:
v = M[1][2]
v.type()

'torch.LongTensor'

In [16]:
# Tensors
T = torch.tensor([[[3,4,5],
                   [6,7,8],
                   [9,8,0]]])
T

tensor([[[3, 4, 5],
         [6, 7, 8],
         [9, 8, 0]]])

In [17]:
T.ndim

3

In [18]:
T.shape

torch.Size([1, 3, 3])

### random tensors

In [19]:
random_tensor = torch.rand(4,5)
random_tensor

tensor([[0.4995, 0.5285, 0.7868, 0.3917, 0.8052],
        [0.6066, 0.3845, 0.9457, 0.5795, 0.0393],
        [0.8615, 0.8994, 0.3648, 0.6056, 0.5615],
        [0.0143, 0.9457, 0.6473, 0.7803, 0.8828]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.shape

torch.Size([4, 5])

In [22]:
# now lets see how we represent an image in tensor format.
random_image_tensor = torch.rand(size=(256, 256, 3)) # 256 - height, 256 - width, 3 colors means 3 channels - RGB.
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([256, 256, 3]), 3)

In [23]:
T2 = torch.rand(3, 2, 1, 4)
T2

tensor([[[[0.2460, 0.2755, 0.7618, 0.2349]],

         [[0.2895, 0.6619, 0.5716, 0.1978]]],


        [[[0.2105, 0.5444, 0.4933, 0.3812]],

         [[0.3953, 0.0961, 0.6841, 0.3612]]],


        [[[0.8869, 0.7585, 0.6975, 0.1833]],

         [[0.2160, 0.3479, 0.0346, 0.4464]]]])

In [24]:
T2.ndim, T2.shape

(4, torch.Size([3, 2, 1, 4]))

### Zeroes and Ones

In [25]:
z = torch.zeros(3, 4)
o = torch.ones(3, 4)
z, o

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [26]:
z.dtype # default datatype is 32-bit integer.

torch.float32

In [27]:
V = torch.tensor([[[1,2,3],
                  [3.0, 6.0, 7.0],
                  [4,5,6]]])
V

tensor([[[1., 2., 3.],
         [3., 6., 7.],
         [4., 5., 6.]]])

In [28]:
V.shape

torch.Size([1, 3, 3])

In [29]:
V.ndim

3

In [30]:
V.size  # it's a function.

<function Tensor.size>

In [31]:
data_type = V.dtype
print(data_type)

torch.float32


### Random Tensors


In [32]:
random_tensor = torch.rand(size=(2,4,3))
random_tensor


tensor([[[0.5376, 0.7587, 0.5079],
         [0.1110, 0.0173, 0.2213],
         [0.0520, 0.7347, 0.8629],
         [0.3263, 0.7959, 0.2495]],

        [[0.3217, 0.9846, 0.0346],
         [0.4177, 0.9148, 0.4932],
         [0.0982, 0.7732, 0.4667],
         [0.1376, 0.9838, 0.3216]]])

In [33]:
random_tensor.dtype

torch.float32

In [34]:
B1 = torch.empty(3,2)
B1

tensor([[-6.2567e+31,  4.3536e-41],
        [-6.2567e+31,  4.3536e-41],
        [ 4.4842e-44,  0.0000e+00]])

In [35]:
B1_zeros = torch.zeros_like(B1)
B1_zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [36]:
B2 = torch.arange(start=1, end = 11, step =  2)
B2

tensor([1, 3, 5, 7, 9])

In [37]:
B3 = torch.tensor([3.0, 6.0, 9.0], dtype = None, device = None, requires_grad = False)

In [38]:
B3.dtype

torch.float32

In [39]:
B3 = B3.type(torch.float16)
B3

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
B4 = torch.tensor([1,2,3], dtype=torch.uint8)

In [41]:
B3 * B4  # here tensors with two different data types are getting multiplied together.

tensor([ 3., 12., 27.], dtype=torch.float16)

### Manipulating tensors

In [42]:
sample_tensor = torch.tensor([1,3,4])
# Addition
sample_tensor + 10

tensor([11, 13, 14])

In [43]:
# Subtraction
sample_tensor - 10

tensor([-9, -7, -6])

In [44]:
# Multiplication
sample_tensor * 10


tensor([10, 30, 40])

In [45]:
# Division
sample_tensor / 10

tensor([0.1000, 0.3000, 0.4000])

In [46]:
# Element Multiplication
some_tensor = torch.tensor([1, 2, 3])
some_tensor * some_tensor


tensor([1, 4, 9])

In [47]:
# Matrix Multiplication or Dot Product
some_tensor.matmul(some_tensor)

tensor(14)

In [48]:
%%time
v = 0
for i in range(len(some_tensor)):
  v += some_tensor[i] * some_tensor[i]
v

CPU times: user 553 µs, sys: 0 ns, total: 553 µs
Wall time: 1.2 ms


tensor(14)

In [49]:
%%time
torch.matmul(some_tensor, some_tensor)

CPU times: user 95 µs, sys: 13 µs, total: 108 µs
Wall time: 113 µs


tensor(14)

In [50]:
torch.matmul(torch.rand(3,2), torch.rand(2,4))

tensor([[0.6571, 0.5605, 0.4646, 0.3590],
        [0.0587, 0.0423, 0.0437, 0.0362],
        [0.6903, 0.6705, 0.4652, 0.3339]])

In [51]:
# One of the common ways you can remove the errors in matrix multiplication is using transpose
C1 = torch.tensor([[1,2,2],
                  [2,3,4]])
C1.shape

torch.Size([2, 3])

In [52]:
C2 = torch.tensor([[5,6,7],
                   [7,8,9]])
C2.shape

torch.Size([2, 3])

In [53]:
# torch.matmul(c1, c2) -> this will throw error as the inner dimensions dont match
torch.matmul(C1, C2.T)

tensor([[31, 41],
        [56, 74]])

In [54]:
C2.T, C2.T.shape

(tensor([[5, 7],
         [6, 8],
         [7, 9]]),
 torch.Size([3, 2]))

In [55]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
x.min()

tensor(0)

In [57]:
torch.max(x)

tensor(90)

In [58]:
torch.mean(x.type(torch.float32))

tensor(45.)