<a href="https://colab.research.google.com/github/santr4/pytorch_for_deep_learning/blob/main/01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.5.1+cu121


In [3]:
# Positions of min and max
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
torch.argmax(x)

tensor(9)

In [5]:
x[9]

tensor(90)

### Reshaping

In [6]:
x = torch.arange(1, 9)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [9]:
x_reshape_0 = x.reshape(1, 8)
x_reshape_0

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [10]:
x_reshape_1 = x.reshape(8, 1)
x_reshape_1

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [12]:
x_reshape_2 = x.reshape(1, 2, 4)
x_reshape_2, x_reshape_2.shape

(tensor([[[1, 2, 3, 4],
          [5, 6, 7, 8]]]),
 torch.Size([1, 2, 4]))

In [14]:
#change the view
z = x.view(1, 8)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [16]:
z[:, 0] = -1
z, x

(tensor([[-1,  2,  3,  4,  5,  6,  7,  8]]),
 tensor([-1,  2,  3,  4,  5,  6,  7,  8]))