# Autograd

In [1]:
import torch

x = torch.randn(3, requires_grad = True)

In [2]:
print(x)

tensor([1.9398, 2.2810, 1.1077], requires_grad=True)


In [3]:
y = x * 2

In [4]:
print(y)

tensor([3.8796, 4.5620, 2.2154], grad_fn=<MulBackward0>)


In [5]:
z = y + y + 4

In [7]:
z

tensor([11.7591, 13.1241,  8.4308], grad_fn=<AddBackward0>)

In [6]:
z.mean()

tensor(11.1047, grad_fn=<MeanBackward0>)

In [10]:
g = torch.tensor([0.1, 0.1, 0.1], dtype = torch.float)

In [11]:
z.backward(g)

/home/santr4/miniconda3/envs/pytorch/lib/python3.12/site-packages/torch/autograd/graph.py:825: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647378361/work/c10/cuda/CUDAFunctions.cpp:108.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


In [12]:
print(x.grad)

tensor([0.4000, 0.4000, 0.4000])


In [13]:
a = torch.tensor([3.0, 2.0, 1.0], dtype = torch.float32, requires_grad=True)
print(a)

tensor([3., 2., 1.], requires_grad=True)


### no gradient function in y

In [14]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():
with torch.no_grad():
    y = x * 2
    print(y)

tensor([3.8796, 4.5620, 2.2154])


In [17]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weights * 2).sum()
    model_output
    model_output.backward()
    print(weights.grad)

tensor([2., 2., 2., 2.])
tensor([4., 4., 4., 4.])
tensor([6., 6., 6., 6.])


In [22]:
w = torch.tensor([1.0, 2.0, 2.0, 3.0], requires_grad=True, dtype=torch.float32)

for i in range(3):
    y = w * 3
    print(y)
    gradient = torch.tensor([0.1, 0.1, 0.1, 0.1], dtype=torch.float32)
    y.backward(gradient)
    print(w.grad)  
    # w.grad.zero_()  - this line is to empty the gradient after each iteration.

tensor([3., 6., 6., 9.], grad_fn=<MulBackward0>)
tensor([0.3000, 0.3000, 0.3000, 0.3000])
tensor([3., 6., 6., 9.], grad_fn=<MulBackward0>)
tensor([0.6000, 0.6000, 0.6000, 0.6000])
tensor([3., 6., 6., 9.], grad_fn=<MulBackward0>)
tensor([0.9000, 0.9000, 0.9000, 0.9000])
