### Tensor Basics


In [1]:
import torch

In [2]:
x = torch.empty(2, 3)

In [3]:
x

tensor([[3.1360e+27, 7.0800e+31, 3.1095e-18],
        [4.7851e+22, 2.8826e+32, 4.4248e+30]])

In [4]:
x = torch.empty(2, 2, 3, 1)

In [5]:
x

tensor([[[[1.6477e-34],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [8.4845e-38],
          [0.0000e+00]]],


        [[[1.0842e-19],
          [0.0000e+00],
          [2.7485e+20]],

         [[1.6928e+22],
          [7.4086e+28],
          [1.7728e+28]]]])

In [6]:
x.dim()

4

In [7]:
x.dtype

torch.float32

In [11]:
y = torch.ones(1, 2, 2, dtype=torch.int16)
y, y.dtype, y.size(), y.dim()

(tensor([[[1, 1],
          [1, 1]]], dtype=torch.int16),
 torch.int16,
 torch.Size([1, 2, 2]),
 3)

In [12]:
# adding two tensors
x = torch.rand(2,2)
y = torch.rand(2, 2)
z = torch.add(x, y)
z

tensor([[0.7394, 1.6779],
        [0.4375, 1.4619]])

In [13]:
x1 = torch.rand(3, 2)
y1 = torch.rand(2, 3)
z1 = torch.add(x1, y1) # this will throw an error because of mismatched dimensions

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [14]:
# likewise we can also do other operations in  pytorch like mul, div, sub, etc.

### slicing

In [15]:
x = torch.rand(5,3)
x

tensor([[0.7190, 0.9767, 0.9531],
        [0.4859, 0.8058, 0.4286],
        [0.3036, 0.2935, 0.5215],
        [0.7217, 0.9533, 0.0440],
        [0.4755, 0.3624, 0.3283]])

In [16]:
x[:, 0]

tensor([0.7190, 0.4859, 0.3036, 0.7217, 0.4755])

In [17]:
print(x[1, 2].item()) # to get the value of a single element tensor

0.4286309480667114


### Reshaping tensors

In [19]:
x = torch.rand(4, 4)
x

tensor([[0.3079, 0.5943, 0.3754, 0.6263],
        [0.6893, 0.7687, 0.7967, 0.3860],
        [0.4949, 0.4008, 0.9710, 0.4912],
        [0.6557, 0.7330, 0.9936, 0.4220]])

In [20]:
y = x.view(2, 8) # same as x.view(-1, 8)

In [24]:
z = x.view(1, 16)
z_1 = x.view(16)
z.dim(), z_1.dim()

(2, 1)

In [22]:
y , z

(tensor([[0.3079, 0.5943, 0.3754, 0.6263, 0.6893, 0.7687, 0.7967, 0.3860],
         [0.4949, 0.4008, 0.9710, 0.4912, 0.6557, 0.7330, 0.9936, 0.4220]]),
 tensor([[0.3079, 0.5943, 0.3754, 0.6263, 0.6893, 0.7687, 0.7967, 0.3860, 0.4949,
          0.4008, 0.9710, 0.4912, 0.6557, 0.7330, 0.9936, 0.4220]]))

In [25]:
import numpy as np

In [29]:
# converting a torch tensor to numpy array
a = torch.ones(1, 2)
b = a.numpy()
a, b

(tensor([[1., 1.]]), array([[1., 1.]], dtype=float32))

In [32]:
# both the tensor and numpy array share same location therefore if we change one the other will change automatically.
c = np.ones(4)
d = torch.from_numpy(c)
d.add_(1)
c, d

(array([2., 2., 2., 2.]), tensor([2., 2., 2., 2.], dtype=torch.float64))